#**********uniscope-driver-modify-file-on-qualcomm-platform*****************#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_CORE) 		+= focaltech_core.o 
obj-$(CONFIG_TOUCHSCREEN_CTL) 				+= focaltech_ctl.o 
obj-$(CONFIG_TOUCHSCREEN_EX_FUN) 			+= focaltech_ex_fun.o 
obj-$(CONFIG_TOUCHSCREEN_FLASH) 			+= focaltech_flash.o 
obj-$(CONFIG_TOUCHSCREEN_GESTURE)			+= focaltech_gesture.o ft_gesture_32bit_lib_v1.0_20140820.a
