#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_TP) += focaltech_upgrade_ft5446u.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_TP) += focaltech_upgrade_ft6336u.o